name = "Carbon"
uuid = "ce4355db-cad5-401f-8b77-e16432d50abd"
authors = ["Vallabh Kansagara"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
